name: Scope Testing

on: [push]

jobs:
  scope:
    runs-on: macOS-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Testing for iOS
        uses: undefinedlabs/scope-for-swift-action@v1
        with:
          dsn: ${{ secrets.SCOPE_DSN }}
          codePath: true
        env:
          SCOPE_RUNNER_ENABLED: YES
          
